my:
   greeting: Hello World from config server - Invoked from Development environment
   values: One, Two, Three

db:
  connection: connection-string-here from develop environment
  host: 127.0.0.1
  port: 1200

test:
  connection: UAT
  host: test-environment
  port: 1300
server:
  port: 9091
